### ISSUE TITLE
Could not find Clojure version due to leading space in version

### ISSUE THREAD

**Issue by jayfranklinn** [polyfy/polylith#226] opened 2022-05-18 11:32 UTC
When typing `poly create workspace name:example top-ns:se.example :commit`

Initial generation yields inside deps.edn:
```
{:aliases  {:dev {:extra-paths ["development/src"]
                  :extra-deps {org.clojure/clojure {:mvn/version " 1.11.0"}}}
```

When starting the repl:
```
Could not find artifact org.clojure:clojure:jar: 1.11.0 in central (https://repo1.maven.org/maven2/)
```

**Comment by tengstrand** [comment] 2022-05-29 16:31
Duplicate of #215 
Thanks for reporting this. This will be fixed in the next release.

**Closed as completed by tengstrand** 2022-05-29 16:31 UTC
