### ISSUE TITLE
Unknown library type: git

### ISSUE THREAD

**Issue by Erdromian** [polyfy/polylith#91] opened 2021-06-02 16:54 UTC
**Describe the bug**
When using a :git/url deps, a project cannot run through 'poly test'.  Instead, we get the error message 
`Unknown library type: git`

**To Reproduce**
1. Add a :git/url dep to your project deps
2. Navigate to the workspace root
3. Run `poly test`

**Expected behavior**
I would expect that :git/url deps would be supported.

**Operating System:**
 - OS: MacOS
 - Version: 11.2.3

**Versions (please complete the following information):**
 - Java: openjdk version "15.0.1" 2020-10-20, OpenJDK Runtime Environment Zulu15.28+13-CA (build 15.0.1+8), OpenJDK 64-Bit Server VM Zulu15.28+13-CA (build 15.0.1+8, mixed mode, sharing)
 - Poly: 0.1.0-alpha9 
 - Brew: Homebrew 3.1.9, Homebrew/homebrew-core (git revision 4c4107224c; last commit 2021-06-0, Homebrew/homebrew-cask (git revision da91e6ae90; last commit 2021-06-02)

**Comment by tengstrand** [comment] 2021-07-01 06:59
Sorry for the inconvenience and late answer. This problem is fixed in the `issue-66` branch, but unfortunately not in the `master` branch, and the problem is that the fix can't be merged into `master` because the code doesn't work the same. As soon as the `issue-66` branch is merged back to `master`, the problem will also be fixed.

**Comment by furkan3ayraktar** [comment] 2021-08-02 10:43
Fixed in #94

**Closed by furkan3ayraktar** 2021-08-02 10:43 UTC
